Create recipe details page
NitBravoA92/recipe-app pull request #30
Opened 2023-10-11 22:24 UTC by NitBravoA92

# 🚩New Implementations: Recipe Details Page

## Hi there! @Luffytaro22 👋

**Here I detail a summary of the new features that have been implemented in this branch:**

- [x] Create routes for RecipesFoodsController and update_status method of RecipesController
- [x] Create the `show` method in RecipesController to display the page of Recipes details
- [x] Create the `total_price` method to calculate the total value of a food - RecipeFood model
- [x] Create **helper methods** in the helper folder to add the logic of formatting data that needs to be displayed in the recipe details views
- [x] Create the partial `_table_recipe_foods_item` to save the HTML code of a table's row - Recipe details page
- [x] Create the show.html.erb page to display the detailed content of a recipe
- [x] Create the `update_status` method in the RecipesController to change the value of the `public` attribute in the Recipe model. 
- [x] Create the `destroy` method in the RecipeFoodsController to remove foods from a recipe
- [x] Update the CSS styles of the app

## ⭐To the code reviewer 👨‍💻

Please, I kindly ask you to review the entire code and verify that all requirements have been met correctly.

if there is any issue 🦯 in this PR, please do list 📃 them in a descriptive 💡 manner and give your best suggestions 🎁 if needed.

2023-10-11 23:30 UTC, Luffytaro22 requested changes
> ## Hi @NitBravoA92 
> Good job so far!
> There are some issues that you still need to work on to go to the next project but you are almost there!

> ## Highlights
> ✅ The layout is identical to the wireframe.
> ✅ Changes the recipe between public and private.
> ✅ Ingredients displays as expected.
> ✅ Brilliant use of module helpers.

> ## Required changes ♻️ 
> _Check the comments under the review._

2023-10-11 23:30 UTC, Luffytaro22 commented on app/views/partials/_table_recipe_foods_item.html.erb
> +      <%= button_to 'Remove', recipe_recipe_food_path(recipe_food), method: :delete, remote: true, class: 'inline-button danger' %>
The remove ingredient button is not working because of this. The recipe_recipe_food_path accepts two parameters: `:recipe_id` and `:id`: `/recipes/:recipe_id/recipe_foods/:id`, but you are just giving the id. In order to solve this you can pass the `@recipe` as a parameter, like this: 
```
recipe_recipe_food_path(@recipe, recipe_food)
```

2023-10-11 23:32 UTC, NitBravoA92 commented on app/views/partials/_table_recipe_foods_item.html.erb
> +      <%= button_to 'Remove', recipe_recipe_food_path(recipe_food), method: :delete, remote: true, class: 'inline-button danger' %>
@Luffytaro22 totally true!! thank you so much! I'm gonna solve it

2023-10-12 00:12 UTC, Luffytaro22 commented on app/views/recipes/show.html.erb
> +      <% if user_signed_in? %>
Sorry, I just noticed this. If I enter on someone else's recipe, I shouldn't be able to see the `toggle button`, `table`, or `Add Ingredient` button, but I can. The problem is that this conditions checks if the current user is `signed in`, which is correct, but that means that every logged user can see this options.

To solve this, I suggest you to use the `can?` method like this:
```
<% if can? :manage, @recipe %>
``` 
In this way, it checks if the current user can `change` the `recipe`.

2023-10-12 02:07 UTC, Luffytaro22 approved these changes
> ## Hi @NitBravoA92 
> Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

2023-10-12 02:14 UTC, merged